### ISSUE TITLE
Fail fast when the command doesn't exist

### ISSUE THREAD

**Issue by chrisroos** [rtomayko/posix-spawn#10]
I stumbled across this when I was trying to use [Albino](https://github.com/github/albino).  It turns out that I didn't have pygments installed (I was sure that I had previously installed it) but the error I was receiving was pretty confusing.

You can replicate the error I was seeing with the following command:

    $ ruby -e"require 'rubygems'; require 'posix/spawn'; POSIX::Spawn::Child.new('non-existent-command')"
    /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn.rb:154:in `_pspawn': No such file or directory - posix_spawnp (Errno::ENOENT)
	from /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn.rb:154:in `pspawn'
	from /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn.rb:137:in `spawn'
	from /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn.rb:274:in `popen4'
	from /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn/child.rb:105:in `exec!'
	from /Users/chrisroos/.rvm/gems/ree-1.8.7-2010.01/gems/posix-spawn-0.3.5/lib/posix/spawn/child.rb:80:in `initialize'
	from -e:1:in `new'
	from -e:1

I wonder if it'd be worth/possible to fail fast with a clear error message when the command you're trying to fork to doesn't exist?

**Comment by rtomayko** [comment]
Closing as fixed. Please reopen if you continue to see this in the wild.
