### ISSUE TITLE
EventMachine hooks

### ISSUE THREAD

**Issue by pietern** [rtomayko/posix-spawn#19]
I created code for an EM-aware `POSIX::Spawn::Child`. It passes the same tests as the blocking version, albeit with #callback and #errback instead of return/raise. Do you think it would be a good idea to smooth it out and import it into this repo, to make sure its interface/features/tests stay in sync with that of `POSIX::Spawn::Child`? I can send a pull request if so.

Thanks!

**Comment by rtomayko** [comment]
Closing as stale and https://github.com/paasio/em-posix-spawn is a thing.
