### ISSUE TITLE
strands process when raising MaximumOutputExceeded

### ISSUE THREAD

**Issue by jfirebaugh** [rtomayko/posix-spawn#26]
Seen when running the grit test suite -- it left a `yes` process ([spawned here](https://github.com/mojombo/grit/blob/3fc864f3c637e06e2fa7a81f6b48a5df58a9bc5b/test/test_git.rb#L54)) consuming 100% CPU.

https://gist.github.com/1903954

**Comment by rtomayko** [comment]
I believe this was fixed some time ago. Please reopen if anyone runs into this.
