### ISSUE TITLE
spawn.rb:187:in `_pspawn': Invalid command name (ArgumentError)

### ISSUE THREAD

**Issue by kikito** [rtomayko/posix-spawn#29]
Hi there,

I just installed git-up as a gem on my new mac (OSX Mountain Lion). Git-up uses posix-spawn as a dependency.

When I execute the git up command, I get the error mentioned in the subject.

I have installed ruby via rvm + gcc for OSX (not the complete XCode tools).

I have used git-up successfully in Ubuntu before. Is there some dependency I must install in OSX for posix-spawn to work properly? Thanks.

**Comment by rtomayko** [comment]
I believe this was fixed a while ago. Closing. Please reopen if this continues to be a problem.
