### ISSUE TITLE
Posix-spawn failed to build on OS X 10.9 with Xcode 5.1 installed

### ISSUE THREAD

**Issue by Arthor** [rtomayko/posix-spawn#50]
While attempting to build posix-spawn on OS X 10.9 with Xcode 5.1 (release) the following error is faced:

```
linking shared-object posix_spawn_ext.bundle
clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: *** [posix_spawn_ext.bundle] Error 1
ERROR:  Error installing git-up:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
```

Apparently this is due to the new behaviour of clang in the latest Xcode. As described in this SO question: http://stackoverflow.com/questions/22352838/ruby-gem-install-json-fails-on-mavericks-and-xcode-5-1-unknown-argument-mul, the root cause is that the clang treats unknown compiler options as error.

**Comment by rtomayko** [comment]
I'm not able to repro this on:

```
$ uname -a
Darwin rtko.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```

Please reopen if this continues to be a problem.
