### ISSUE TITLE
ChildTest#test_max_with_stubborn_child hangs on OSX

### ISSUE THREAD

**Issue by dblock** [rtomayko/posix-spawn#52]
In Child#exec!, you get the expected `POSIX::Spawn::MaximumOutputExceeded` exception, but then 

```ruby
::Process.kill('TERM', pid) rescue nil
```

seems to have no effect on OSX, the process still lingers.

**Comment by rtomayko** [comment]
Closing as no repro w/ https://github.com/rtomayko/posix-spawn/issues/53. Please reopen if you see the issue.
