### ISSUE TITLE
0.3.4 release is completely broken on linux

### ISSUE THREAD

**Issue by tmm1** [rtomayko/posix-spawn#7]
Most of the tests fail due to `POSIX_SPAWN_SETSIGDEF` in f64981262c0c2e8eca449380a84dc09d9675617d

    Started
    .FFFFFFFFF.FFFF.FFFFFF...................................EFFF.FFFFFFFFFFFF.FFFFFFFFF.FFFFFF.F.....F.FF
    Finished in 0.748392 seconds.

    102 tests, 275 assertions, 53 failures, 1 errors

However, when I remove that, the `test_max_stubborn_child` test hangs on `rbx` + `osx`:

    Started
    ..............
    ^CF.......................................................................................
    Finished in 47.334512 seconds.

      1) Failure:
    test_max_with_stubborn_child(ChildTest)
        [./test/test_child.rb:72:in `test_max_with_stubborn_child'
         kernel/bootstrap/array.rb:76:in `each'
         kernel/bootstrap/array.rb:76:in `each']:
    <POSIX::Spawn::MaximumOutputExceeded> exception expected but was
    Class: <Interrupt>
    Message: <"Thread has been interrupted">

**Comment by rtomayko** [comment]
Pretty sure this was all fixed up.
