### ISSUE TITLE
gcc error while installing gem on 32bit OS

### ISSUE THREAD

**Issue by kk1986** [rtomayko/posix-spawn#74]
Unable to install this gem on one of my 32bit server and running with RHEL5.9

[root@server-test1 ~]# /usr/bin/gem install posix-spawn-0.3.11.gem
Building native extensions.  This could take a while...
ERROR:  Error installing posix-spawn-0.3.11.gem:
        ERROR: Failed to build gem native extension.

/usr/bin/ruby extconf.rb
creating Makefile

make
gcc -I. -I/usr/lib/ruby/1.8/i386-linux -I/usr/lib/ruby/1.8/i386-linux -I. -D_FILE_OFFSET_BITS=64   -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -fno-strict-aliasing  -fPIC  -Wall   -c posix-spawn.c
cc1: error: unrecognized command line option "-fstack-protector"
cc1: error: invalid parameter `ssp-buffer-size'
posix-spawn.c:1: error: bad value (generic) for -mtune= switch
make: **\* [posix-spawn.o] Error 1

Gem files will remain installed in /usr/lib/ruby/gems/1.8/gems/posix-spawn-0.3.11 for inspection.
Results logged to /usr/lib/ruby/gems/1.8/gems/posix-spawn-0.3.11/ext/gem_make.out
[root@server-test1 ~]
[root@server-test1 ~] arch
i686
[root@server-test1 ~]

**Comment by tmm1** [comment]
This is due to a broken compiler or ruby installation.
