### ISSUE TITLE
deprecation warning in ruby 2.4

### ISSUE THREAD

**Issue by vchepkov** [rtomayko/posix-spawn#76]
After upgrading to ruby 2.4, gem generates warnings:

/usr/local/lib/ruby/gems/2.4.0/gems/posix-spawn-0.3.12/lib/posix/spawn.rb:467: warning: constant ::Fixnum is deprecated

**Comment by Tafkas** [comment]
Same for me.

**Comment by jcoyne** [comment]
Looks like this is fixed in master, we just need @rtomayko or @tmm1 to push a new release.

**Comment by felixbuenemann** [comment]
I think this has been fixed in #77 and released in 0.3.13 and this issue can be closed.

**Comment by smaximov** [comment]
Can confirm, the warning is gone in 0.3.13.
