### ISSUE TITLE
posix_spawn_ext.so: undefined symbol: rb_fix2int

### ISSUE THREAD

**Issue by sgparry** [rtomayko/posix-spawn#78]
I am trying to get Gitlab CE 8.5.8+dfsg-5 working on Ubuntu 16.04 32 bit, using the package in the "universe" repo. That GitLab package installs latest posix_spawn as part of it's install. 0.3.13 causes this error to be raised (in the sidekiq log):

posix_spawn_ext.so: undefined symbol: rb_fix2int

0.3.11 does not appear to have this issue. I have not tried 0.3.12.
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]
Ubuntu 16.04.2 LTS
Linux 4.4.50-rh54-20170220215556.xenU.i386 #1 SMP Mon Feb 20 22:04:23 UTC 2017 i686 i686 i686 GNU/Linux

**Comment by tmm1** [comment]
cc @charliesome https://github.com/rtomayko/posix-spawn/pull/77

**Comment by pterjan** [comment]
Commit 1ba8fe8a2cc2eb326fe75a443282481313033feb broke building on 32 bits architecture as rb_fix2int is only defined if SIZEOF_INT < SIZEOF_LONG

The code previously used RB_FIX2INT which would be RB_FIX2LONG on 32 bits, which was probably a bug and causing a warning as it got assigned to an int but at least it compiled.

I don't know the clean way to raise if it doesn't fit in an int, but can try to find out later.

**Comment by pterjan** [comment]
Ah sorry, if int and long have same size, it's fine, so RB_FIX2INT is the way to go

**Comment by rgstephens** [comment]
Installing 0.3.12 worked for me.

**Comment by sgparry** [comment]
Thanks guys for working on this, I may try this again later but I am thinking of moving to 64bit server anyhow.

**Comment by standin000** [comment]
thanks, gollum depends it, now it's latest version 0.3.13, I install 0.3.12 which is OK, I hope release 0.3.14 will fix it.
