### ISSUE TITLE
add jruby support

### ISSUE THREAD

**Issue by tmm1** [rtomayko/posix-spawn#8]
definitely need this before 1.0

with the new cext support in 1.6, the extension actually compiles and works. we'll need to fallback to a pure jruby implementation if you try to pass fds through, but any simple usage can probably use the cext directly.

i also found a way to get exit status out of IO.popen4 on jruby: http://jira.codehaus.org/browse/JRUBY-5684

**Comment by rtomayko** [comment]
Closing as stale for now. If JRuby is a thing someone can dedicate time too, please reopen.
