### ISSUE TITLE
release 0.3.14 containing #83

### ISSUE THREAD

**Issue by flokli** [rtomayko/posix-spawn#86]
Currently, posix_spawn is broken on 32 bit architectures due to #83 not being in 0.3.13, but no later release available.

At least Gitlab and Mastodon both seem to be affected by this, see https://github.com/tootsuite/mastodon/pull/7517 and https://gitlab.awesome-it.de/overlays/gitlab/issues/57.

Can you please release a 0.3.14, containing the fix from #83, so people don't have to manually pin to 0.3.12 or master?

**Comment by flokli** [comment]
ping @rtomayko ;-)

**Comment by kaspergrubbe** [comment]
ping @rtomayko

**Comment by killua99** [comment]
c´mon @rtomayko :D just merge and release

**Comment by tmm1** [comment]
v0.3.14 has been released.
