### ISSUE TITLE
Release 0.3.15 for Ruby 2.7

### ISSUE THREAD

**Issue by parkr** [rtomayko/posix-spawn#89]
Hey @tmm1! Opening this issue to track the next patch release of posix-spawn. It includes some fixes for Ruby 2.7 warnings.

See: https://github.com/rtomayko/posix-spawn/pull/88#issuecomment-656304896

/cc @thepwagner

**Comment by tmm1** [comment]
313f2abd4b9b5e737615178e0b353114481b9ab8

**Comment by parkr** [comment]
Thank you so much, @tmm1! ❇️ ✨
